version: "3"
services:
    ssl-standalone:
        image: certbot/certbot:latest
        command: certonly --standalone --agree-tos --cert-name hernrup.se --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCRYPT_DRY --verbose
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
        ports:
            - "80:80"
            - "443:443"
    ssl:
        image: certbot/certbot:latest
        command: certonly --webroot --cert-name hernrup.se --webroot-path=/data/letsencrypt --agree-tos --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCRYPT_DRY
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt

    nginx:
        image: nginx
        restart: always
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
            - .data/etc/.htpasswd:/etc/.htpasswd
        ports:
            - "80:80"
            - "443:443"

    plex:
        image: linuxserver/plex
        restart: always
        volumes:
            - .data/etc/plex:/config
            - ${TV_DIR}:/data/tvshows
            - ${MOVIE_DIR}:/data/movies
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
            - "1900:1900/udp"

    sonarr:
        image: linuxserver/sonarr
        restart: always
        volumes:
            - ".data/etc/sonarr:/config"
            - "${TV_DIR}:/tv"
            - .data/data/downloads:/downloads

    nzb:
        image: linuxserver/sabnzbd
        restart: always
        volumes:
            - .data/data/downloads:/downloads
            - .data/data/nzb/incomplete:/incomplete-downloads
            - .data/etc/nzb:/config

    potatoe:
        image: linuxserver/couchpotato
        restart: always
        volumes:
            - ".data/etc/couchpotatoe:/config"
            - ".data/data/downloads:/downloads"
            - "${MOVIE_DIR}:/movies"

    registry:
        restart: always
        image: registry:2
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /etc/.htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - ".data/docker-registry:/var/lib/registry"
            - .data/etc/letsencrypt/live/hernrup.se:/certs
            - /data/etc/.htpasswd:/etc/.htpasswd
