version: "3"
services:
    ssl:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/data/letsencrypt -d test.hernrup.se --agree-tos --email mikael@hernrup.se --verbose --renew-by-default
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
    nginx:
        image: nginx
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/mime.types:/etc/nginx/mime.types
        ports:
            - "80:80"
            - "443:443"
    req:
        image: linuxserver/plexrequests
    plex:
        image: linuxserver/plex
    sonarr:
        image: linuxserver/sonarr
    nzb:
        image: linuxserver/sabnzbd
    potatoe:
        image: linuxserver/couchpotato
