version: "3"
services:
    ssl-standalone:
        image: certbot/certbot:latest
        command: certonly --standalone --agree-tos --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCRYPT_DRY --verbose
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
        ports:
            - "80:80"
            - "443:443"
    ssl:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/data/letsencrypt --agree-tos --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCRYPT_DRY
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt

    nginx:
        image: nginx
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
        ports:
            - "80:80"
            - "443:443"
    req:
        image: linuxserver/plexrequests
        volumes:
            - .data/etc/plexrequests:/config
        ports:
            - "3000:3000"
        environment:
            #- URL_BASE=/req.hernrup.se
            - TEST=TEST

    plex:
        image: linuxserver/plex
        volumes:
            - .data/etc/plex:/config
            - .data/data/plex:/data/tvshows
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
              #- "5353:5353/udp"
            - "1900:1900/udp"

    sonarr:
        image: linuxserver/sonarr
        ports:
            - "8989:8989"
        volumes:
            - .data/etc/sonarr:/config
            - .data/data/sonarr/tv:/tv
            - .data/data/downloads/tv:/downloads

    nzb:
        image: linuxserver/sabnzbd
        volumes:
        - ".data/etc/nzb:/datadir"
        - ".data/data/nzb:/media"
        ports:
            - "8080:8080"

    potatoe:
        image: linuxserver/couchpotato
        volumes:
            - ".data/etc/couchpotatoe:/config"
            - ".data/data/couchpotatoe:/downloads"
            - "${MOVIE_DIR}:/movies"
        ports:
            - "5050:5050"
