version: "3"
services:
    ssl-standalone:
        image: certbot/certbot:latest
        command: certonly --standalone --agree-tos --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCRYPT_DRY --verbose
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
        ports:
            - "80:80"
            - "443:443"
    ssl:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/data/letsencrypt --agree-tos --email $LETSENCRYPT_EMAIL --renew-by-default $LETSENCRYPT_DOMAINS $LETSENCYPT_DRY
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt

    nginx:
        image: nginx
        volumes:
            - .data/etc/letsencrypt:/etc/letsencrypt
            - .data/data/letsencrypt:/data/letsencrypt
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./nginx/ssl.conf:/etc/nginx/ssl.conf
            - ./nginx/logging.conf:/etc/nginx/logging.conf
        ports:
            - "80:80"
            - "443:443"
    req:
        image: linuxserver/plexrequests

    plex:
        image: linuxserver/plex
        volumes:
            - .data/etc/plex:/config
            - .data/data/plex:/data/tvshows
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
              #- "5353:5353/udp"
            - "1900:1900/udp"

    sonarr:
        image: linuxserver/sonarr
        ports:
            - "8989:8989"
        volumes:
            - .data/etc/sonarr:/config
            - .data/data/sonarr/tv:/tv
            - .data/data/downloads/tv:/downloads

    nzb:
        image: linuxserver/sabnzbd
    potatoe:
        image: linuxserver/couchpotato
